name: '_COSMO Alpaca - Sync Configs'

on:
  workflow_call:
    inputs:
      backendUrl:
        description: COSMO Alpaca backend URL
        required: true
        type: string
      additionalSecrets:
        description: Comma-separated list of additional secret names to always include
        required: false
        type: string
        default: 'GitHubPackagesContext,licenseFileUrl'
      additionalVariables:
        description: Comma-separated list of additional variable names to always include
        required: false
        type: string
        default: 'ALGoOrgSettings,ALGoRepoSettings'
      mode:
        description: GetAndUpdate searches AL-Go settings files and backend, Update only queries backend
        required: false
        type: string
        default: 'GetAndUpdate'

defaults:
  run:
    shell: pwsh

env:
  ALGoOrgSettings: ${{ vars.ALGoOrgSettings }}
  ALGoRepoSettings: ${{ vars.ALGoRepoSettings }}
  ALPACA_BACKEND_URL: ${{ inputs.backendUrl }}
  # Settings must contain at least one property for ReadSecrets to function correctly.
  Settings: '{"placeholder": "value"}'

jobs:
  SyncAlpacaConfigs:
    name: Sync COSMO Alpaca Configs
    runs-on: [ ubuntu-latest ]
    steps:

      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Get configs for sync
        id: GetConfigsForSync
        uses: cosmoconsult/Alpaca-Actions/Actions/GetConfigsForSync@feature/configsync
        with:
          shell: pwsh
          token: ${{ secrets.GITHUB_TOKEN }}
          mode: ${{ inputs.mode }}
          additionalSecrets: ${{ inputs.additionalSecrets }}
          allVariables: ${{ toJson(vars) }}
          additionalVariables: ${{ inputs.additionalVariables }}
      
      - name: Read secrets
        id: ReadSecrets
        uses: microsoft/AL-Go-Actions/ReadSecrets@v8.0
        with:
          shell: pwsh
          gitHubSecrets: ${{ toJson(secrets) }}
          getSecrets: '${{ steps.GetConfigsForSync.outputs.secretsForSync }}'
      
      - id: SyncConfigs
        name: Sync Configs
        uses: cosmoconsult/Alpaca-Actions/Actions/SyncConfigs@feature/configsync
        with:
          shell: pwsh
          token: ${{ secrets.GITHUB_TOKEN }}
          secretsJson: ${{ steps.ReadSecrets.outputs.Secrets }}
          variablesJson: ${{ steps.GetConfigsForSync.outputs.Variables }}
