name: '[OBSOLETE] Sync COSMO Alpaca Secrets'

on:
  workflow_call:

jobs:
  Obsolete:
    name: This workflow is obsolete
    runs-on: ubuntu-latest
    steps:
    - run: echo "::error::This workflow is obsolete and only exists for automatic removal in target repositories on update AL-Go system files. Please use the 'AlpacaSyncConfigs.yaml' workflow instead."
